### ISSUE TITLE
Init command for default configuration

### ISSUE THREAD

**Issue by ptcar2009** [inspr/core-legacy#15]
**Is your feature request related to a problem? Please describe.**
The default values for the configuration are set as localhost with the root scope. That makes it confusing for new users and creates a need for documentation querying.

**Describe the solution you'd like**
Create an init command that prompts the user for the configuration he wants, and state  (if there is no configuration set) that the user should try the init command.

**Describe alternatives you've considered**
We could prompt without asking for the init command, just prompt if not initialized.

**Comment by brenordr** [comment]
@ptcar2009 How should this work?
like `npm init` ? and we ask for cluster id and also look to initialize the cluster too?

**Comment by ptcar2009** [comment]
@brenordr yeah, that's the basic idea.
