### ISSUE TITLE
Move project to a vanity import path

### ISSUE THREAD

**Issue by brenordr** [inspr/core-legacy#18]
**Is your feature request related to a problem? Please describe.**
Recently we moved the project to github. But to conclude the migration we should update the imports not to `github.com/inspr/inspr` but to `inspr.io/inspr`, `inspr.dev/inspr`, `inspr.dev/x`, `inspr.dev/v1` or something along those lines.

**Describe the solution you'd like**
Use the path `inspr.io/x/` or `inspr.dev/x/`
I prefer the .dev with x but we can choose any of them

**Describe alternatives you've considered**
We can keep just the github but in some sense it can be a problem for people using the product.
for example if we need to move the repos.

**Additional context**
Some references:

https://sagikazarmark.hu/blog/vanity-import-paths-in-go/
https://medium.com/@JonNRb/making-a-golang-vanity-url-f56d8eec5f6c

The process can be very simple.
Google prepared a tool for it:  https://github.com/GoogleCloudPlatform/govanityurls 
We need to put it as an dapp in our cluster and expose it as a service, then point inspr.io or inspr.dev to the correct path.

**Comment by brenordr** [comment]
Just a note, since our organization will open source more tools in the future and we are likely to use go 😆 
will be good to use a standard path model, x looks good visually and to type but is more common use the package name itself.
Such as `inspr.dev/inspr` or `inspr.io/inspr`
and for packages such as cli we can do `inspr.io/cli` `inspr.dev/cli`

if we use x, then we can consider it special case for inspr core. Honestly it looks fine to me, just isn't quite standard.
since we have been following the standards the most, I propose to consider `inspr.dev/inspr`

**Comment by ptcar2009** [comment]
We should make a proper inspr deployment cluster then, so that the development process doesn't fudge up the proxy hosting. We can use the current cluster, just set up a production inspr instance.

**Comment by brenordr** [comment]
@ptcar2009 Yes, I agree. It can't go down otherwise users will have issues in download.
It can be the same cluster we will use for inspr.com
