### ISSUE TITLE
Kubernetes config for k8s doesn't use helm

### ISSUE THREAD

**Issue by brenordr** [inspr/core-legacy#34]
The port, host and a few other values are hard coded for k8s configs at ./build/k8s
@ptcar2009 I'm not sure if this file is used, but if it is should we consider move it to a helm chart?

**Comment by ptcar2009** [comment]
Actually, these files are deprecated, we are using the definitions inside helm.

**Comment by brenordr** [comment]
@ptcar2009 I’ll open a PR deleting them

**Comment by brenordr** [comment]
Fixed in #33
